export { db, pgPool } from "./client";
export {
  UserRole,
  CatalogOrderStatus,
  PaymentStatus,
  DiscountType,
} from "@prisma/client";
export type {
  Account,
  AuditLog,
  BaseColorOption,
  CatalogOrder,
  CatalogOrderItem,
  CatalogProduct,
  CatalogProductSizeInventory,
  Category,
  Coupon,
  CouponUsage,
  LoginOtp,
  PasswordResetToken,
  Payment,
  Prisma,
  ProductImage,
  RateLimitBucket,
  RolePermission,
  SavedAddress,
  Session,
  ShoeModelOption,
  StoreSetting,
  User,
  VerificationToken,
} from "@prisma/client";
